Tenant qualify Passive-STS
wso2-extensions/identity-outbound-auth-passive-sts pull request #40
Opened 2020-07-06 12:56 UTC by emswbandara

Addresses https://github.com/wso2/product-is/issues/8314

2020-07-15 14:39 UTC, ashensw approved these changes

2020-07-15 14:46 UTC, mefarazath requested changes

2020-07-15 14:46 UTC, mefarazath commented on components/org.wso2.carbon.identity.application.authenticator.passive.sts/src/main/java/org/wso2/carbon/identity/application/authenticator/passive/sts/manager/PassiveSTSManager.java
> +            redirectUrl = FrameworkUtils.appendQueryParamsStringToUrl(loginPage, "?wa=" + action + "&wreply=" +
Can we avoid having a ? In the query string?
If the loginPage already has query params this would result in an invalid URL.

2020-07-17 12:34 UTC, mefarazath approved these changes

2020-07-22 05:03 UTC, merged